version: '3.8'

services:
  nginx:
    image: nginx:stable-bookworm
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
      - ./proxy/logs:/var/log/nginx
      - ./static:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always


  backend:
    image: go-backend:latest
    container_name: go_backend
    build:
      context: ./app
      dockerfile: ./Dockerfile
    command: tail -f /dev/null
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    restart: always